
services:
  backend:
    build:
      context: ./backendApp
      dockerfile: DockerFile
    ports:
      - "8100:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    ports:
      - "3000:3000"