
services:
  backend:
    build:
      context: ./backendApp
      dockerfile: DockerFile
    ports:
      - "8100:8000"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #     - LANG=C.UTF-8
  #   volumes:
  #     - ./frontend:/app
  #     - ./data:/app/data
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network